/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhan_haoqi_sign_Sign */
#define UTF_8 "UTF-8"
#ifndef _Included_com_zhan_haoqi_sign_Sign
#define _Included_com_zhan_haoqi_sign_Sign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhan_haoqi_sign_Sign
 * Method:    getSign
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhan_haoqi_sign_Sign_getSign
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_zhan_haoqi_sign_Sign
 * Method:    getAESKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhan_haoqi_sign_Sign_getAESKey
        (JNIEnv *, jclass, jobject);
JNIEXPORT jstring JNICALL Java_com_zhan_haoqi_sign_Sign_getPubKey
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
